services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: kachau
      POSTGRES_USER: kachau
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: >
            sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DATABASE_URL: postgis://kachau:${DB_PASSWORD}@db:5432/kachau
    depends_on:
      - db

volumes:
  pgdata:




